# site settings
title: J. Prescott Sanders
subtitle: There and Back Again!
email: youremailaddress@gmail.com
description: There and Back Again!
baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Indianapolis
state: IN
zip_code: 
country: United States of America
phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jprescottsanders
gitlab_url: https://gitlab.com/u/jprescottsanders
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/prescottsanders

# build settings
markdown: kramdown

sass:
  style: compressed
